name: Create release on tag

on:
  push:

jobs:
  create-release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install parse-changelog
        run: cargo +stable install parse-changelog --locked
      - name: Check there is a changelog for tag
        run: parse-changelog CHANGELOG.md 0.1.3
