name: Run tests
on:
  push:
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        # runs-on: [ubuntu-22.04, windows-2022, macos-12]
        runs-on: [windows-2022]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install dependencies
        run: pip install hatch==1.9.1
      - name: Setup rust toolchain
        run: |
          rustup set default-host x86_64-pc-windows-gnu
        if: runner.os == 'Windows'
      - name: Set up Rust
        run: rustup show
      - name: Run Lint
        run: hatch run lint:style
      - name: Run tests
        run: hatch run test.py3.8:test -k test_module_path_variable
